/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cyradar.ui.components;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author phinc27
 */
public final class ClosableTabComponent extends javax.swing.JPanel {

    public void setTitle(String title) {
        this.label.setText(title);
        this.tf.setText(title);
    }

    public String getTitle() {
        return this.label.getText();
    }

    public void setCloseButtonToolTip(String tooltip) {
        this.button.setToolTipText(tooltip);
    }

    public void addCloseActionListener(ActionListener listener) {
        button.addActionListener(listener);
    }

    /**
     * Creates new form ClosableTabComponent
     */
    public ClosableTabComponent() {
        initComponents();
        tf.setVisible(false);
    }

    public ClosableTabComponent(String title) {
        initComponents();
        setTitle(title);
        tf.setVisible(false);
    }

    public void startEditting() {
        label.setVisible(false);
        tf.setText(label.getText());
        tf.setVisible(true);
        tf.requestFocusInWindow();
        tf.setCaretPosition(tf.getText().length());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel(){
            @Override
            public Dimension getPreferredSize() {
                if (getText().isEmpty()) {
                    return new Dimension(14, 14);
                }
                return super.getPreferredSize();
            }
        };
        tf = new javax.swing.JTextField(){
            @Override
            public Dimension getPreferredSize() {
                if (getText().isEmpty()) {
                    return new Dimension(14, 14);
                }
                return super.getPreferredSize();
            }
        };
        button = new javax.swing.JButton();

        setOpaque(false);

        label.setText("Untitled");
        label.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 4, 0, 6));
        label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelMouseReleased(evt);
            }
        });
        add(label);

        tf.setBackground(new java.awt.Color(0, 0, 0, 0));
        tf.setText("Untitled");
        tf.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 4));
        tf.setOpaque(false);
        tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFocusLost(evt);
            }
        });
        tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfKeyReleased(evt);
            }
        });
        add(tf);

        button.setText("×");
        button.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setFocusable(false);
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
        });
        add(button);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        JButton b = (JButton) evt.getSource();
        b.setForeground(Color.red);
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        JButton b = (JButton) evt.getSource();
        b.setForeground(Color.black);
    }//GEN-LAST:event_buttonMouseExited

    private void tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFocusLost
        label.setText(tf.getText());
        tf.setVisible(false);
        label.setVisible(true);
    }//GEN-LAST:event_tfFocusLost

    private void tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            label.setText(tf.getText());
            tf.setVisible(false);
            label.setVisible(true);
        }
    }//GEN-LAST:event_tfKeyReleased

    private void labelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMousePressed
        if (evt.getClickCount() == 2) {
            label.setVisible(false);
            tf.setText(label.getText());
            tf.setVisible(true);
            tf.requestFocusInWindow();
            tf.setCaretPosition(tf.getText().length());
            return;
        }
        Container parentContainer = SwingUtilities.getAncestorOfClass(JTabbedPane.class, (JLabel) evt.getSource());
        if (parentContainer != null) {
            JTabbedPane parent = (JTabbedPane) parentContainer;
            MouseEvent parentEvent = SwingUtilities.convertMouseEvent((Component) evt.getSource(), evt, parent);
            parent.dispatchEvent(parentEvent);
        }
    }//GEN-LAST:event_labelMousePressed

    private void labelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMouseReleased
        Container parentContainer = SwingUtilities.getAncestorOfClass(JTabbedPane.class, (JLabel) evt.getSource());
        if (parentContainer != null) {
            JTabbedPane parent = (JTabbedPane) parentContainer;
            MouseEvent parentEvent = SwingUtilities.convertMouseEvent((Component) evt.getSource(), evt, parent);
            parent.dispatchEvent(parentEvent);
        }
    }//GEN-LAST:event_labelMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JLabel label;
    private javax.swing.JTextField tf;
    // End of variables declaration//GEN-END:variables
}
