/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cyradar.ui.components;

import com.cyradar.models.InterceptConfiguration;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JRadioButton;

/**
 *
 * @author phinc27
 */
public class InterceptConfigurationForm extends javax.swing.JPanel {
    
    private InterceptConfiguration configuration;
    
    private class RBTargetUrlTypeItemListener implements ItemListener {
        
        @Override
        public void itemStateChanged(ItemEvent e) {
            if (e.getStateChange() == ItemEvent.DESELECTED) {
                return;
            }
            JRadioButton rb = (JRadioButton) e.getSource();
            targetURL.setEditable(rb == rbTargetUrlTypeCustom);
            cbUseRegex.setEnabled(rb == rbTargetUrlTypeCustom);
        }
    }

    /**
     * Creates new form InterceptConfigurationForm
     */
    public InterceptConfigurationForm() {
        initComponents();
        RBTargetUrlTypeItemListener urlTypeListener = new RBTargetUrlTypeItemListener();
        rbTargetUrlTypeAll.addItemListener(urlTypeListener);
        rbTargetUrlTypeInScope.addItemListener(urlTypeListener);
        rbTargetUrlTypeCustom.addItemListener(urlTypeListener);
    }
    
    public void setConfiguration(InterceptConfiguration configuration) {
        this.configuration = configuration;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTargetMessageType = new javax.swing.ButtonGroup();
        bgTargetUrlType = new javax.swing.ButtonGroup();
        targetPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbTargetMessageTypeRequest = new javax.swing.JRadioButton();
        rbTargetMessageTypeResponse = new javax.swing.JRadioButton();
        rbTargetMessageTypeBoth = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbTargetUrlTypeAll = new javax.swing.JRadioButton();
        rbTargetUrlTypeInScope = new javax.swing.JRadioButton();
        rbTargetUrlTypeCustom = new javax.swing.JRadioButton();
        targetURL = new javax.swing.JTextField();
        cbUseRegex = new javax.swing.JCheckBox();
        switch1 = new com.cyradar.ui.components.Switch();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        stagePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        paramName = new javax.swing.JTextField();
        cboxUrlDecodeBefore = new javax.swing.JCheckBox();
        cboxUrlEncodeAfter = new javax.swing.JCheckBox();
        interceptStageForm2 = new com.cyradar.ui.components.InterceptStageForm();

        targetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Targets"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Choose which target urls will be handled by this tab");

        bgTargetMessageType.add(rbTargetMessageTypeRequest);
        rbTargetMessageTypeRequest.setSelected(true);
        rbTargetMessageTypeRequest.setText("Requests");

        bgTargetMessageType.add(rbTargetMessageTypeResponse);
        rbTargetMessageTypeResponse.setText("Responses");

        bgTargetMessageType.add(rbTargetMessageTypeBoth);
        rbTargetMessageTypeBoth.setText("Both");

        jLabel2.setText("with URLs");

        bgTargetUrlType.add(rbTargetUrlTypeAll);
        rbTargetUrlTypeAll.setSelected(true);
        rbTargetUrlTypeAll.setText("All");

        bgTargetUrlType.add(rbTargetUrlTypeInScope);
        rbTargetUrlTypeInScope.setText("In Burp scope");

        bgTargetUrlType.add(rbTargetUrlTypeCustom);
        rbTargetUrlTypeCustom.setText("Custom");

        targetURL.setEditable(false);

        cbUseRegex.setText("Use regex");
        cbUseRegex.setEnabled(false);

        javax.swing.GroupLayout targetPanelLayout = new javax.swing.GroupLayout(targetPanel);
        targetPanel.setLayout(targetPanelLayout);
        targetPanelLayout.setHorizontalGroup(
            targetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(targetPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(targetPanelLayout.createSequentialGroup()
                .addGroup(targetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(targetPanelLayout.createSequentialGroup()
                        .addComponent(rbTargetMessageTypeRequest)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2))
                    .addComponent(rbTargetMessageTypeResponse)
                    .addComponent(rbTargetMessageTypeBoth))
                .addGap(42, 42, 42)
                .addGroup(targetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbTargetUrlTypeInScope)
                    .addComponent(rbTargetUrlTypeAll)
                    .addGroup(targetPanelLayout.createSequentialGroup()
                        .addComponent(rbTargetUrlTypeCustom)
                        .addGap(18, 18, 18)
                        .addGroup(targetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbUseRegex)
                            .addComponent(targetURL, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        targetPanelLayout.setVerticalGroup(
            targetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(targetPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(targetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTargetMessageTypeRequest)
                    .addComponent(jLabel2)
                    .addComponent(rbTargetUrlTypeAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(targetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTargetMessageTypeResponse)
                    .addComponent(rbTargetUrlTypeInScope))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(targetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTargetMessageTypeBoth)
                    .addComponent(rbTargetUrlTypeCustom)
                    .addComponent(targetURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(cbUseRegex))
        );

        switch1.setText("switch1");

        jButton1.setText("Apply");

        jButton2.setText("Discard");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        stagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter Handling"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Parameter:");

        cboxUrlDecodeBefore.setSelected(true);
        cboxUrlDecodeBefore.setText("Automatically URL - decode value before modifying");

        cboxUrlEncodeAfter.setSelected(true);
        cboxUrlEncodeAfter.setText("Automatically URL - encode value if moreified");

        javax.swing.GroupLayout stagePanelLayout = new javax.swing.GroupLayout(stagePanel);
        stagePanel.setLayout(stagePanelLayout);
        stagePanelLayout.setHorizontalGroup(
            stagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stagePanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(paramName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboxUrlDecodeBefore)
                    .addComponent(cboxUrlEncodeAfter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(interceptStageForm2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        stagePanelLayout.setVerticalGroup(
            stagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(paramName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboxUrlDecodeBefore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboxUrlEncodeAfter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interceptStageForm2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(targetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(switch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(switch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(targetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTargetMessageType;
    private javax.swing.ButtonGroup bgTargetUrlType;
    private javax.swing.JCheckBox cbUseRegex;
    private javax.swing.JCheckBox cboxUrlDecodeBefore;
    private javax.swing.JCheckBox cboxUrlEncodeAfter;
    private com.cyradar.ui.components.InterceptStageForm interceptStageForm2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField paramName;
    private javax.swing.JRadioButton rbTargetMessageTypeBoth;
    private javax.swing.JRadioButton rbTargetMessageTypeRequest;
    private javax.swing.JRadioButton rbTargetMessageTypeResponse;
    private javax.swing.JRadioButton rbTargetUrlTypeAll;
    private javax.swing.JRadioButton rbTargetUrlTypeCustom;
    private javax.swing.JRadioButton rbTargetUrlTypeInScope;
    private javax.swing.JPanel stagePanel;
    private com.cyradar.ui.components.Switch switch1;
    private javax.swing.JPanel targetPanel;
    private javax.swing.JTextField targetURL;
    // End of variables declaration//GEN-END:variables
}
